### ISSUE TITLE
[Feature Request] Better weapon support besides empty hands and sword.

### ISSUE THREAD

**Issue by fzrdwa123456** [MarkusBordihn/BOs-Easy-NPC-Epic-Fight#3]
After I gave the NPCS weapons other than empty hands and sword, the other weapons seemed to have no effect without attack animations, and some NPCS did not support the use of weapons

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. Could you please provide 1-2 example which weapons are not working.
I used the Epic Fight example on their page, which is supporting axe, hoe, pickaxe, shovel and sword.
See: https://github.com/MarkusBordihn/BOs-Easy-NPC-Epic-Fight/blob/2d4e40353abb716158b52814058e7998d7d5f61a/Common/src/main/resources/data/easy_npc_epic_fight/epicfight_mobpatch/skeleton.json#L40

You can create a data pack if you want to adjust these animation for your own needs.

**Comment by fzrdwa123456** [comment]
> Thanks for the feedback. Could you please provide 1-2 example which weapons are not working. I used the Epic Fight example on their page, which is supporting axe, hoe, pickaxe, shovel and sword. See:
> 
> https://github.com/MarkusBordihn/BOs-Easy-NPC-Epic-Fight/blob/2d4e40353abb716158b52814058e7998d7d5f61a/Common/src/main/resources/data/easy_npc_epic_fight/epicfight_mobpatch/skeleton.json#L40
> 
> You can create a data pack if you want to adjust these animation for your own needs.

Some types of weapons like the big sword and the long spear and so on because I haven't played this mod for a while I don't really remember
