### ISSUE TITLE
Npc's won't use two handed Weapons  animations ...

### ISSUE THREAD

**Issue by 0megacat** [MarkusBordihn/BOs-Easy-NPC-Epic-Fight#7]
**Describe the bug**
If an Npc has any weapons aside from fists it wont use teh weapons not correctly. There is no animation for the EpicFight weapons and the Npc's only attack if the "Perform Melee Attack"-box is checked. If not they ignore any mob which they are supposed to attack.

**To Reproduce**

1. Create an EasyNpc with EpicFight Integration.
2. Equip the Npc with any weapon from the EpicFight Mod
3. Check the "Attack Villagers"-box under objectives.attack
4. Spawn an Villager
5. See error
6. If the "Perform Melee Attack"-box is checked, the Npc will attack the villager but not correctly

**Expected behavior**
That the Npc would fight an mob like a player can use an EpicFight-weapon.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**
Easy NPC ( easy_npc_1.20.1-4.3.3.jar )
Easy NPC - Epic Fight ( easy_npc_1.20.1-4.0.0.jar )
Epic Fight ( EpicFight-20.7.4.jar )

Screenshots:
![2024-04-11_03 28 26](https://github.com/MarkusBordihn/BOs-Easy-NPC-Epic-Fight/assets/166671967/5d5d427b-7ead-4e36-a691-a8c24273edb3)
![2024-04-11_03 28 37](https://github.com/MarkusBordihn/BOs-Easy-NPC-Epic-Fight/assets/166671967/f90cd3e3-24b9-4566-bd6f-a152183a2c3c)
![2024-04-11_03 28 52](https://github.com/MarkusBordihn/BOs-Easy-NPC-Epic-Fight/assets/166671967/5fbfa9ae-7a94-485b-8429-feed50d8d1f9)

**Comment by MarkusBordihn** [comment]
Thanks for the feedback.

> the Npc's only attack if the \"Perform Melee Attack\"-box is checked

This is by design, the NPCs only using the models and animations but not any other features like fractions other actions like a normal entity over the '/summon' command would do.

> Npc has any weapons aside from fists it wont use teh weapons not correctly

Could you please clarify what "correctly" means in this context?

I'm not using epic fight myself and just followed the epic fight developer guide, which provides only a very basic animation definition.

**Comment by 0megacat** [comment]
> 
> > Npc has any weapons aside from fists it wont use teh weapons not correctly
> 
> Could you please clarify what "correctly" means in this context?
> 
With correctly I meant the fighting style animation for the weapons from EpicFight. If a player uses them it swings around (see gif)
![PHVYrrq](https://github.com/MarkusBordihn/BOs-Easy-NPC-Epic-Fight/assets/166671967/3fcd4d6e-7b1c-4d3d-88db-b187a9869637)
The Npc does not uses those animations. Thats what I meant ^^

**Comment by MechRW** [comment]
I also have this problem.
In the issue where the NPC I left you a message about only preparing animations and not attacking animations
He is the same.
Please use the epic battle experience yourself, or watch the video I have provided for you.
The adaptation methods currently provided by you and the adaptation methods provided by epic battle authors,
I added an adaptive animation to the skull according to the data package method provided by the epic battle author.
The result is that the skull has animated standby actions, but no attack animations. Even the sword animation of the original epic battle skeleton has been discarded.

Perhaps our approach is consistent.
But none of them apply. (As demonstrated by this issue, NPCs do not have any attack animations.)

**Comment by MechRW** [comment]
> > > NPC除了拳头之外没有任何武器，它不会正确使用武器
> > 
> > 
> > 您能否澄清一下在这种情况下“正确”的含义？
> 
> 没错，我的意思是 EpicFight 中武器的战斗风格动画。如果玩家使用它们，它会四处摆动（见 gif） ![PHVYrrq](https://private-user-images.githubusercontent.com/166671967/321638144-3fcd4d6e-7b1c-4d3d-88db-b187a9869637.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTk2ODYsIm5iZiI6MTcxMjg1OTM4NiwicGF0aCI6Ii8xNjY2NzE5NjcvMzIxNjM4MTQ0LTNmY2Q0ZDZlLTdiMWMtNGQzZC04OGRiLWIxODdhOTg2OTYzNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxODE2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGRjNzQ4ZDZhNWQxZGUyMTI4NzhjOTEyNjgxM2M1YmUwMzRkZmQ4ZTI0Y2ExODJhNzI1NWRlYzAyYmYzMTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GOQZ7ldBXBAu9ydc7-2bXzgJDupOg-i8HRgGibP4HbE) [ ![PHVYrrq](https://private-user-images.githubusercontent.com/166671967/321638144-3fcd4d6e-7b1c-4d3d-88db-b187a9869637.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTk2ODYsIm5iZiI6MTcxMjg1OTM4NiwicGF0aCI6Ii8xNjY2NzE5NjcvMzIxNjM4MTQ0LTNmY2Q0ZDZlLTdiMWMtNGQzZC04OGRiLWIxODdhOTg2OTYzNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxODE2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGRjNzQ4ZDZhNWQxZGUyMTI4NzhjOTEyNjgxM2M1YmUwMzRkZmQ4ZTI0Y2ExODJhNzI1NWRlYzAyYmYzMTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GOQZ7ldBXBAu9ydc7-2bXzgJDupOg-i8HRgGibP4HbE) ](https://private-user-images.githubusercontent.com/166671967/321638144-3fcd4d6e-7b1c-4d3d-88db-b187a9869637.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTk2ODYsIm5iZiI6MTcxMjg1OTM4NiwicGF0aCI6Ii8xNjY2NzE5NjcvMzIxNjM4MTQ0LTNmY2Q0ZDZlLTdiMWMtNGQzZC04OGRiLWIxODdhOTg2OTYzNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxODE2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGRjNzQ4ZDZhNWQxZGUyMTI4NzhjOTEyNjgxM2M1YmUwMzRkZmQ4ZTI0Y2ExODJhNzI1NWRlYzAyYmYzMTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GOQZ7ldBXBAu9ydc7-2bXzgJDupOg-i8HRgGibP4HbE) [ ](https://private-user-images.githubusercontent.com/166671967/321638144-3fcd4d6e-7b1c-4d3d-88db-b187a9869637.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTk2ODYsIm5iZiI6MTcxMjg1OTM4NiwicGF0aCI6Ii8xNjY2NzE5NjcvMzIxNjM4MTQ0LTNmY2Q0ZDZlLTdiMWMtNGQzZC04OGRiLWIxODdhOTg2OTYzNy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxODE2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGRjNzQ4ZDZhNWQxZGUyMTI4NzhjOTEyNjgxM2M1YmUwMzRkZmQ4ZTI0Y2ExODJhNzI1NWRlYzAyYmYzMTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GOQZ7ldBXBAu9ydc7-2bXzgJDupOg-i8HRgGibP4HbE) NPC 不使用这些动画。这就是我的意思^^
Even fists do not have boxing animations. NPC will only approach enemies for collisions.
![only attack without any animation](https://github.com/MarkusBordihn/BOs-Easy-NPC-Epic-Fight/assets/162135883/7beb29a1-3113-4e8b-af40-7ccfb5ac1132)
The author of Epic Fit did indeed provide this method and created a data package. in 1.18 it was works.

The result is shown in the figure. In the higher version(1.20.1), it directly turned into this pile of poo.

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. I could not really reproduce the issue with "no animations".

https://github.com/MarkusBordihn/BOs-Easy-NPC-Epic-Fight/assets/12183293/5a96e035-bdaa-4ae1-93ee-566fd4693c9e

I could reproduce that double handed swords and animation are not implemented.

**Comment by MechRW** [comment]
> Thanks for the feedback. I could not really reproduce the issue with "no animations".
> 
>  easy_npc_epic_fight_issue_7.mp4 
> I could reproduce that double handed swords and animation are not implemented.

Man, maybe you should do this
The videos you posted are all monsters like zombie skeletons,
But it doesn't seem like the so-called humanoid NPC (please try again using humanoid NPC)
The skeleton generated by the epic fit by default is not the original archer. They will instead directly use weapons such as great swords and spears.
You can try not giving them the original weapons, but rather the unique Tachi, Sword, and Spear of epic fight,or wom weapon(maybe crash your game,be careful)
They will only display weapon standby animations.
Attack animations are not available.


the video is here:
https://www.bilibili.com/video/BV1Wz421C7bX

**Comment by 0megacat** [comment]
> > Thanks for the feedback. I could not really reproduce the issue with "no animations".
> > easy_npc_epic_fight_issue_7.mp4
> > I could reproduce that double handed swords and animation are not implemented.
>
> Man, maybe you should do this The videos you posted are all monsters like zombie skeletons, But it doesn't seem like the so-called humanoid NPC (please try again using humanoid NPC) The skeleton generated by the epic fit by default is not the original archer. They will instead directly use weapons such as great swords and spears. You can try not giving them the original weapons, but rather the unique Tachi, Sword, and Spear of epic fight,or wom weapon(maybe crash your game,be careful) They will only display weapon standby animations. Attack animations are not available.

And the weapons used in the video are not from EpicFight. The problem is that the Npcs wont use the EpicFight weapons which include Dagger, Greatsword, Spear and more. The normal minecraft sword does function normally

**Comment by MechRW** [comment]
I wrote a data packet and tested it,
The problem is not with the type of weapon
But NPC never uses the action of epic fight at all.
